# Generated by Django 6.0.2 on 2026-04-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='can_transfer',
            field=models.BooleanField(default=False, help_text='Permite a los cajeros de esta sucursal realizar transferencias de productos', verbose_name='Puede hacer transferencias'),
        ),
    ]
