# Generated by Django 6.0.2 on 2026-04-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_can_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono de la sucursal (ej: 55 1234 5678)', max_length=20, verbose_name='Teléfono'),
        ),
    ]
