# Generated by Django 6.0.2 on 2026-04-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='can_manage_finished',
            field=models.BooleanField(default=False, help_text='Permite a los cajeros de esta sucursal preparar productos terminados a partir de recetas', verbose_name='Puede gestionar productos terminados'),
        ),
    ]
