# Generated by Django 6.0.2 on 2026-04-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('SALE', 'Venta'), ('TRANSFER_OUT', 'Transferencia Salida'), ('TRANSFER_IN', 'Transferencia Entrada'), ('PRODUCTION_OUT', 'Salida por Producción'), ('PRODUCTION_IN', 'Entrada por Producción')], max_length=20),
        ),
    ]
