# Generated by Django 6.0.2 on 2026-02-26 22:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0003_alter_product_options_remove_product_barcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProfitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('units_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_profitability', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability', to='products.product')),
            ],
            options={
                'verbose_name': 'Rentabilidad de producto',
                'verbose_name_plural': 'Rentabilidad de productos',
                'ordering': ['-date', '-profit'],
                'unique_together': {('product', 'branch', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProfitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual')], max_length=20)),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_summaries', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Resumen de ganancias',
                'verbose_name_plural': 'Resúmenes de ganancias',
                'ordering': ['-date'],
                'unique_together': {('branch', 'period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PurchasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Válido desde')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Válido hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_prices', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'Precio de compra',
                'verbose_name_plural': 'Precios de compra',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['product', 'branch', '-valid_from'], name='earnings_pu_product_3a874a_idx')],
            },
        ),
    ]
