# Generated by Django 6.0.2 on 2026-03-16 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0001_initial'),
        ('products', '0003_alter_product_options_remove_product_barcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseprice',
            name='earnings_pu_product_3a874a_idx',
        ),
        migrations.AddIndex(
            model_name='purchaseprice',
            index=models.Index(fields=['product', '-valid_from'], name='earnings_pu_product_b65374_idx'),
        ),
        migrations.RemoveField(
            model_name='purchaseprice',
            name='branch',
        ),
    ]
