# Generated by Django 6.0.2 on 2026-02-15 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('diets', '0001_initial'),
        ('products', '0002_product_is_ingredient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietbaseingredient',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_ingredient': True}, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.CreateModel(
            name='DietCajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets_cajero', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diet_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex_diets', to='diets.diet')),
            ],
        ),
        migrations.CreateModel(
            name='DietCajeroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.FloatField(default=0)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diets.dietcajero')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('diet', 'product')},
            },
        ),
    ]
