# Generated by Django 6.0.2 on 2026-02-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_added',
            field=models.BooleanField(default=False, help_text='Indica si los productos de este pedido ya fueron agregados al inventario'),
        ),
    ]
