# Generated by Django 6.0.2 on 2026-02-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='price_type',
            field=models.CharField(choices=[('kg', 'Por Kg'), ('bulk', 'Por Bulto'), ('wholesale', 'Mayoreo'), ('special', 'Especial')], default='kg', max_length=20),
        ),
    ]
