# Generated by Django 6.0.2 on 2026-03-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cliente_nombre',
            field=models.CharField(blank=True, default='Cliente Mostrador', max_length=200, verbose_name='Nombre del cliente'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
    ]
