# Generated by Django 6.0.2 on 2026-04-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_cliente_direccion_sale_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia')], default='CASH', max_length=20),
        ),
    ]
