# Generated by Django 6.0.2 on 2026-04-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_remove_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Indica si este producto se produce a partir de otros (receta)', verbose_name='Es producto terminado'),
        ),
    ]
